# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-16 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='upated',
            new_name='updated',
        ),
    ]
