# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:53
from __future__ import unicode_literals

import buyer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20190616_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='order_image',
            field=models.ImageField(blank=True, null=True, upload_to=buyer.models.get_image_path),
        ),
    ]
